=== pds-technology/devkit-c/doc/Standards/energyml/api/witsml/v1.3.1/obj_capSubscriber.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema  
	elementFormDefault="qualified" 
	attributeFormDefault="unqualified"
	targetNamespace="http://www.witsml.org/api/131" 
	xmlns=          "http://www.witsml.org/api/131" 
	xmlns:witsml=   "http://www.witsml.org/api/131"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	version="1.3.1">
	<!--                                                         -->
	<!-- POSC License Agreement
	This file is distributed under the POSC License Agreement at
	http://www.posc.org/about/license.shtml.
	Use of this file constitutes agreement with the POSC License Agreement.
	-->
	<!--                                                         -->
	<xsd:include schemaLocation="cs_contact.xsd"/>
	<xsd:include schemaLocation="cs_dataTypes.xsd"/>
	<!--                                                         -->
	<xsd:annotation>
		<xsd:documentation>Defines the WITSML capSubscriber object, used to 
		communicate the detailed API Capabilities of the WITSML Subscriber.
		API Capabilities are used to further define and narrow the functionality 
		defined by the API specification.
		</xsd:documentation>
	</xsd:annotation>
	<!--                                                         -->
	<xsd:element name="capSubscribers" type="witsml:obj_capSubscribers">
		<xsd:annotation>
			<xsd:documentation>The WITSML API mandated plural root element which allows 
			multiple singular objects to be sent. The plural name is formed by adding
			an "s" to the singular name.
			Present only for consistency with other WITSML data objects (multiple 
			capSubscriber elements are not allowed). 
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<!--                                                         -->
	<xsd:complexType name="obj_capSubscribers">
		<xsd:sequence>
			<xsd:element name="capSubscriber" type="witsml:obj_capSubscriber" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Defines the singular Subscriber Capabilities 
					(capSubscriber) element; only one can be specified. 
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="version" type="witsml:str16" fixed="1.3.1" use="optional">
			<xsd:annotation>
				<xsd:documentation>API schema version.  It is optional.
				If the version is specified, its value must be set equal to the value specified by the 
				version's fixed attribute. Note that this is different from the data schema version.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<!--                                                         -->
	<xsd:complexType name="obj_capSubscriber">
		<xsd:annotation>
			<xsd:documentation>Defines the singular Subscriber Capabilities data 
			type (obj_capSubscriber).
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="contact" type="witsml:cs_contact" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Contact information for Subscriber.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="description" type="witsml:str4096" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Description of Subscriber.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>	
			<xsd:element name="name" type="witsml:str64" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Name of the Subscriber.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>	
			<xsd:element name="vendor" type="witsml:str64" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Vendor of the Subscriber software.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>	
			<xsd:element name="version" type="witsml:str64" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Subscriber software Executable Program version (identification only; use apiVers to determine Subscriber's API Capability).
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>	
			<xsd:element name="schemaVersion" type="witsml:str64" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>A comma separated list of schema versions (without spaces) that are supported 
					by the subscriber. The oldest version should be listed first, followed by the next 
					oldest, etc. </xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="apiVers" type="witsml:str16" use="required">
			<xsd:annotation>
				<xsd:documentation>Version of the API specification to which this Publisher conforms. 
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
</xsd:schema>

=== pds-technology/devkit-c/doc/Standards/energyml/api/witsml/v1.3.1/XML_Examples/capSubscriber_no_xsl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--   		Example of capSubscriber document 		-->
<capSubscribers 
	xmlns="http://www.witsml.org/api/131" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.witsml.org/api/131 
			    http://www.witsml.org/api/131/obj_capSubscriber.xsd" 
	version="1.3.1">
	<capSubscriber apiVers="1.2.0">
		<contact>
			<name>Subscriber #1 at ABC corp.</name>
			<email>myEmailAddress@abc.com</email>
			<phone>888-123-4567</phone>
		</contact>
		<description>Engineering departent at ABC corp.</description>
		<name>John Smith</name>
		<vendor>Acme Downhole Software</vendor>
		<version>1.2.0.1451</version>
		<schemaVersion>1.2.0</schemaVersion>
	</capSubscriber>
</capSubscribers>
