=== pds-technology/devkit-c/doc/Standards/energyml/data/completions/v1.0/completions_v1.0/ancillary/cs_enumValues.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
	elementFormDefault="qualified" 
	attributeFormDefault="unqualified" 
	targetNamespace="http://www.witsml.org/schemas/1series" 
	xmlns:witsml="http://www.witsml.org/schemas/1series" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	version="1.4.0">
	<!--                                                         -->
	<!-- Energistics License Agreement
	This file is distributed under the Energistics License Agreement at
	http://www.energistics.org
	Use of this file constitutes agreement with the Energistics License Agreement.
	-->
	<!--                                                         -->
	<xsd:include schemaLocation="../xsd_schemas/typ_dataTypes.xsd"/>
	<!--                                                         -->
	<xsd:annotation>
		<xsd:documentation>Schema for listing standardized values as an alternative 
		to using an enumeration in XML Schema. This schema is not intended to be part 
		of a WITSML data object.</xsd:documentation>
	</xsd:annotation>
	<!--                                                         -->
	<xsd:element name="enumListSet" type="witsml:enumListSet">
		<xsd:annotation>
			<xsd:documentation>A container for enumeration lists.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<!--                                                         -->
	<xsd:complexType name="enumListSet">
		<xsd:sequence>
			<xsd:element name="enumList" type="witsml:enumList" minOccurs="1" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>A single enumeration list.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="version" type="witsml:schemaVersionString" use="required">
			<xsd:annotation>
			<xsd:documentation>Data object schema version.  The fourth level must match the 
			version of the schema constraints (enumerations and XML loader files) that are assumed
			by the document instance.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<!--                                                         -->
	<xsd:complexType name="enumList">
		<xsd:sequence>
			<xsd:element name="name" type="witsml:str32" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The name of the list.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="description" type="witsml:commentString" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>A description of the list. 
					This specifies what the individual values represent.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="namingSystem" type="witsml:nameString" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The naming system within which the terms are defined.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="value" type="witsml:enumValue" minOccurs="1" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>A description of an enumberation value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!--                                                         -->
	<xsd:complexType name="enumValue">
		<xsd:sequence>
			<xsd:element name="name" type="witsml:kindString" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The name of the value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="description" type="witsml:commentString" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>A description of the value. </xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="version" type="witsml:nameString" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The version when the value was added.
					The string should match the content of the root version attribute of the schema.
					For example, "1.4.0.0".</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="deprecated" type="witsml:nameString" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>A non blank version indicates that the value has
					been deprecated and may be removed in future versions.
					The string should match the content of the root version attribute of the schema.
					For example, "1.4.0.0".</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="replacedBy" type="witsml:nameString" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>The value to use as a replacement for a deprecated value.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:choice minOccurs="0" maxOccurs="1">
				<xsd:sequence>
					<xsd:element name="lithoType" type="witsml:EnumValueLithoType" minOccurs="1" maxOccurs="1">
						<xsd:annotation>
							<xsd:documentation>For lithology qualifiers, the type of qualifier: "noun", "adjective" or "both". 
							For a qualifier which has a type of "both", the "noun" form must be specified as the qualifier value
							and an adjective form must be listed as a variant.
							The interpretation of whether a specified qualifier value represents a noun or a adjective is 
							defined by its association with either an interval (adjective) or point (noun).</xsd:documentation>
						</xsd:annotation>
					</xsd:element>
					<xsd:element name="variantOf" type="witsml:kindString" minOccurs="0" maxOccurs="unbounded">
						<xsd:annotation>
							<xsd:documentation>The name of the lithology qualifier for which this qualifier 
							represents a variation of the same underlying concept. 
							A variant will always represent either an adjective or a noun but not both.</xsd:documentation>
						</xsd:annotation>
					</xsd:element>
					<xsd:element name="isLithology" type="xsd:boolean" minOccurs="0" maxOccurs="unbounded">
						<xsd:annotation>
							<xsd:documentation>True ("true" or "1") indicates that the qualifier is also in the LithologyType list.
							False ("false" or "0") indicates otherwise.</xsd:documentation>
						</xsd:annotation>
					</xsd:element>
					<xsd:element name="isMatrixCement" type="xsd:boolean" minOccurs="0" maxOccurs="unbounded">
						<xsd:annotation>
							<xsd:documentation>True ("true" or "1") indicates that the qualifier is also in the MatrixCementType list.
							False ("false" or "0") indicates otherwise.</xsd:documentation>
						</xsd:annotation>
					</xsd:element>
				</xsd:sequence>
				<xsd:sequence>
					<xsd:element name="extensionDataType" type="witsml:PrimitiveType" minOccurs="1" maxOccurs="1">
						<xsd:annotation>
							<xsd:documentation>For extensions, the underlying data type of the value. </xsd:documentation>
						</xsd:annotation>
					</xsd:element>
					<xsd:element name="extensionMaximumSize" type="witsml:positiveCount" minOccurs="0" maxOccurs="1">
						<xsd:annotation>
							<xsd:documentation>For extensions, the maximum number of charactetrs in a string value. </xsd:documentation>
						</xsd:annotation>
					</xsd:element>
					<xsd:element name="extensionMeasureClass" type="witsml:MeasureClass" minOccurs="0" maxOccurs="1">
						<xsd:annotation>
							<xsd:documentation>For extensions, defines the measure class associated with the temm.
							This controls the allowed units of measure. 
							If this is specified then the value must be defined with a unit of measure.</xsd:documentation>
						</xsd:annotation>
					</xsd:element>
					<xsd:element name="extensionPath" type="witsml:descriptionString" minOccurs="0" maxOccurs="unbounded">
						<xsd:annotation>
							<xsd:documentation>For extensions, defines the path to the allowed location in the schema
							where the extension is allowed. 
							This should begin at the singular object level  (e.g., "/well/commonData/extension"). 
							A relative location will allow it in any object (i.e., ".//commonData/extension").
							A relative location within the object will allow it at any location within that object
							(e.g., "/opsReport//commonData/extension").</xsd:documentation>
						</xsd:annotation>
					</xsd:element>
				</xsd:sequence>
				<xsd:sequence>
					<xsd:element name="measureRepresentativeUOM" type="witsml:uomString" minOccurs="0" maxOccurs="1">
						<xsd:annotation>
							<xsd:documentation>For measure classes, defines a representative uom. </xsd:documentation>
						</xsd:annotation>
					</xsd:element>
					<xsd:element name="measureBaseForConversion" type="witsml:uomString" minOccurs="0" maxOccurs="1">
						<xsd:annotation>
							<xsd:documentation>For measure classes, defines the base uom for conversion. </xsd:documentation>
						</xsd:annotation>
					</xsd:element>
					<xsd:element name="measureUom" type="witsml:uomString" minOccurs="1" maxOccurs="unbounded">
						<xsd:annotation>
							<xsd:documentation>For measure classes, defines an allowed uom for the class. </xsd:documentation>
						</xsd:annotation>
					</xsd:element>
				</xsd:sequence>
				<xsd:sequence>
					<xsd:choice>
						<xsd:element name="realtimeDataType" type="witsml:EnumValueRealtimeType" minOccurs="0" maxOccurs="unbounded">
							<xsd:annotation>
								<xsd:documentation>For realtime data, defines the underlying type data associated with this term.</xsd:documentation>
							</xsd:annotation>
						</xsd:element>
						<xsd:element name="realtimeMeasureClass" type="witsml:MeasureClass" minOccurs="0" maxOccurs="1">
							<xsd:annotation>
								<xsd:documentation>For realtime data, defines the measure class associated with the term.
								This controls the allowed units of measure. 
								If this is specified then the value must be defined with a unit of measure.
								All measure values inherently have a numeric data type.</xsd:documentation>
							</xsd:annotation>
						</xsd:element>
					</xsd:choice>
				</xsd:sequence>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	<!--                                                         -->
	<xsd:complexType name="emumValueLithoVariant" final="#all">
		<xsd:annotation>
			<xsd:documentation>A variant of a qualifer. A qualifier can have both adjective and noun forms.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:extension base="witsml:abstractNameString">
				<xsd:attribute name="form" type="witsml:EnumValueLithoType" use="required">
					<xsd:annotation>
						<xsd:documentation>The kind of qualifier form. This should be either "adjective" or "noun".</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<!--                                                         -->
	<xsd:simpleType name="EnumValueLithoType">
		<xsd:annotation>
			<xsd:documentation>Lithology qualifier types.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="witsml:abstractTypeEnum">
			<xsd:enumeration value="noun">
 				<xsd:annotation>
  					<xsd:documentation>Qualifiers which are isolated or spot occurrences suggesting 
  					that these components are `included' in a lithology and does not imply a 
  					lithology type (for example, a single occurrence of a fossil).
					A qualifier which is specified as a point value (top=bottom) should be interpreted 
					as representing the noun form.</xsd:documentation>
  				</xsd:annotation>
 			</xsd:enumeration>
			<xsd:enumeration value="adjective">
 				<xsd:annotation>
  					<xsd:documentation>Qualifiers which are components or attributes of the lithology 
  					occurring/prevailing over a depth range, or over the whole lithology; an adjective 
  					should be used as a further definition of an existing lithology type (for example, 
  					types of cementation or other diagenetic effects would be expressed using adjectives).
					A qualifier which is specified over a depth range should be interpreted as representing
					the adjective form.</xsd:documentation>
  				</xsd:annotation>
 			</xsd:enumeration>
 			<xsd:enumeration value="both">
 				<xsd:annotation>
  					<xsd:documentation>A qualifier which can have both adjective and noun forms.
					If the qualifier is specified either over a depth range then it should be interpreted
					as representing its adjective form. If the qualifier is specified at a point then it
					should be interpreted as its noun form.</xsd:documentation>
  				</xsd:annotation>
 			</xsd:enumeration>
 			<xsd:enumeration value="unknown">
 				<xsd:annotation>
  					<xsd:documentation>The value is not known. This value should not be used
					in normal situations. All reasonable attempts should be made to determine
					the appropriate value. Use of this value may result in rejection in some situations.</xsd:documentation>
  				</xsd:annotation>
 			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!--                                                         -->
	<xsd:simpleType name="EnumValueRealtimeType">
		<xsd:annotation>
			<xsd:documentation>Lithology qualifier types.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="witsml:abstractTypeEnum">
			<xsd:enumeration value="string">
				<xsd:annotation>
					<xsd:documentation>The value is a string. This is also appropriate for a short list of integer codes (e.g., "1", 2" or "3") or for booleans.</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="numeric">
				<xsd:annotation>
					<xsd:documentation>The value is a number and fractional component is allowed.</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="integer">
				<xsd:annotation>
					<xsd:documentation>Specialization of numeric. The value is a whole number. That is, a fractional component is not allowed.</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
 			<xsd:enumeration value="unknown">
 				<xsd:annotation>
  					<xsd:documentation>The value is not known. This value should not be used
					in normal situations. All reasonable attempts should be made to determine
					the appropriate value. Use of this value may result in rejection in some situations.</xsd:documentation>
  				</xsd:annotation>
 			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!--                                                         -->
</xsd:schema>

=== pds-technology/devkit-c/doc/Standards/energyml/data/witsml/v1.3.1.1/ancillary/enumValues.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/WitsmlEnumList.xsl" type="text/xsl" media="screen"?>

<!--
This file is distributed under the POSC License Agreement at
http://www.posc.org/about/license.shtml.
Use of this file constitutes agreement with the POSC License Agreement.
-->

<enumListSet 
	xmlns="http://www.witsml.org/schemas/131" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.witsml.org/schemas/131 
			   ../cs_enumValues.xsd" 
	version="1.3.1.1">
	<enumList>
		<name>ActivityCode</name>
		<description>Activity codes.</description>
		<namingSystem>WITSML</namingSystem>
		<value>
			<name>abandonment</name>
			<description>abandonment</description>
		</value>
		<value>
			<name>abandonment -- log plugs</name>
			<description>A specialization of 'abandonment'.</description>
		</value>
		<value>
			<name>abandonment -- run plugs</name>
			<description>A specialization of 'abandonment'.</description>
		</value>
		<value>
			<name>abandonment -- wait on cement</name>
			<description>A specialization of 'abandonment'.</description>
		</value>
		<value>
			<name>casing, cement</name>
			<description>casing and cement</description>
		</value>
		<value>
			<name>casing, cement -- circulate, cement</name>
			<description>A specialization of 'casing, cement': circulate and cement</description>
		</value>
		<value>
			<name>casing, cement -- other</name>
			<description>A specialization of 'casing, cement'.</description>
		</value>
		<value>
			<name>casing, cement -- rig up, run casing</name>
			<description>A specialization of 'casing, cement': rig up and run casing</description>
		</value>
		<value>
			<name>casing, cement -- rig up, run liner</name>
			<description>A specialization of 'casing, cement': rig up and run liner</description>
		</value>
		<value>
			<name>casing, cement -- wait on cement</name>
			<description>A specialization of 'casing, cement'.</description>
		</value>
		<value>
			<name>completion operations</name>
			<description>After reaching total depth, any operations for completing the well and bringing it on production - no further detail is known.</description>
		</value>
		<value>
			<name>completion operations -- rig up</name>
			<description>Rig up completion equipment.</description>
		</value>
		<value>
			<name>completion operations -- tear down</name>
			<description>Tear down completion equipment.</description>
		</value>
		<value>
			<name>completion operations -- testing </name>
			<description>Pre-production flow testing in the well completion phase.</description>
		</value>
		<value>
			<name>completion operations -- running liner</name>
			<description>Running the production liner.</description>
		</value>
		<value>
			<name>completion operations -- gravel packing</name>
			<description>Completion operation for producing zones.</description>
		</value>
		<value>
			<name>completion operations -- logging</name>
			<description>Production logging tool runs.</description>
		</value>
		<value>
			<name>cond mud, circulate</name>
			<description>condition mud and circulate</description>
		</value>
		<value>
			<name>cond mud, circulate -- boulder or gravel</name>
			<description>A specialization of 'cond mud, circulate'.</description>
		</value>
		<value>
			<name>cond mud, circulate -- casing</name>
			<description>A specialization of 'cond mud, circulate'.</description>
		</value>
		<value>
			<name>cond mud, circulate -- cementing</name>
			<description>A specialization of 'cond mud, circulate'.</description>
		</value>
		<value>
			<name>cond mud, circulate -- circulate samples</name>
			<description>A specialization of 'cond mud, circulate'.</description>
		</value>
		<value>
			<name>cond mud, circulate -- coring</name>
			<description>A specialization of 'cond mud, circulate'.</description>
		</value>
		<value>
			<name>cond mud, circulate -- drilling</name>
			<description>A specialization of 'cond mud, circulate'.</description>
		</value>
		<value>
			<name>cond mud, circulate -- fishing</name>
			<description>A specialization of 'cond mud, circulate'.</description>
		</value>
		<value>
			<name>cond mud, circulate -- gumbo attack</name>
			<description>A specialization of 'cond mud, circulate'.</description>
		</value>
		<value>
			<name>cond mud, circulate -- logging</name>
			<description>A specialization of 'cond mud, circulate'.</description>
		</value>
		<value>
			<name>cond mud, circulate -- lost circulation</name>
			<description>A specialization of 'cond mud, circulate'.</description>
		</value>
		<value>
			<name>cond mud, circulate -- well control</name>
			<description>A specialization of 'cond mud, circulate'.</description>
		</value>
		<value>
			<name>coring</name>
			<description>coring</description>
		</value>
		<value>
			<name>coring -- conventional</name>
			<description>A specialization of 'coring'.</description>
		</value>
		<value>
			<name>coring -- flow check</name>
			<description>A specialization of 'coring'.</description>
		</value>
		<value>
			<name>coring -- laydown barrel</name>
			<description>A specialization of 'coring'.</description>
		</value>
		<value>
			<name>coring -- oriented</name>
			<description>A specialization of 'coring'.</description>
		</value>
		<value>
			<name>coring -- plastic sleeve</name>
			<description>A specialization of 'coring'.</description>
		</value>
		<value>
			<name>coring -- rig up core barrel</name>
			<description>A specialization of 'coring'.</description>
		</value>
		<value>
			<name>coring -- sponge</name>
			<description>A specialization of 'coring'.</description>
		</value>
		<value>
			<name>cut, slip drilling line</name>
			<description>cut and slip drilling line</description>
		</value>
		<value>
			<name>deviation survey</name>
			<description>deviation survey</description>
		</value>
		<value>
			<name>deviation survey -- dir multi-shot</name>
			<description>A specialization of 'deviation survey': directional multi-shot</description>
		</value>
		<value>
			<name>deviation survey -- dir single shot</name>
			<description>A specialization of 'deviation survey': directional single shot</description>
		</value>
		<value>
			<name>deviation survey -- drift</name>
			<description>A specialization of 'deviation survey'.</description>
		</value>
		<value>
			<name>deviation survey -- gyro</name>
			<description>A specialization of 'deviation survey'.</description>
		</value>
		<value>
			<name>deviation survey -- MWD</name>
			<description>A specialization of 'deviation survey'.</description>
		</value>
		<value>
			<name>dir work</name>
			<description>directional work</description>
		</value>
		<value>
			<name>dir work -- horizontal drilling</name>
			<description>A specialization of 'dir work'.</description>
		</value>
		<value>
			<name>dir work -- motor drilling</name>
			<description>A specialization of 'dir work'.</description>
		</value>
		<value>
			<name>dir work -- orient</name>
			<description>A specialization of 'dir work'.</description>
		</value>
		<value>
			<name>dir work -- rotary drilling</name>
			<description>A specialization of 'dir work'.</description>
		</value>
		<value>
			<name>dir work -- slant drilling</name>
			<description>A specialization of 'dir work'.</description>
		</value>
		<value>
			<name>DST</name>
			<description>drill stem test</description>
		</value>
		<value>
			<name>DST -- cased hole</name>
			<description>A specialization of 'DST'.</description>
		</value>
		<value>
			<name>DST -- lay down tools</name>
			<description>A specialization of 'DST'.</description>
		</value>
		<value>
			<name>DST -- open hole</name>
			<description>A specialization of 'DST'.</description>
		</value>
		<value>
			<name>DST -- open hole closed chamber</name>
			<description>A specialization of 'DST'.</description>
		</value>
		<value>
			<name>DST -- rig up tools</name>
			<description>A specialization of 'DST'.</description>
		</value>
		<value>
			<name>drilling</name>
			<description>drilling</description>
		</value>
		<value>
			<name>drilling -- casing</name>
			<description>A specialization of 'drilling'.</description>
		</value>
		<value>
			<name>drilling -- connection</name>
			<description>A specialization of 'drilling'.</description>
		</value>
		<value>
			<name>drilling -- drill cement, float equip</name>
			<description>A specialization of 'drilling': drill out cement and/or float equipment</description>
		</value>
		<value>
			<name>drilling -- flow check</name>
			<description>A specialization of 'drilling'.</description>
		</value>
		<value>
			<name>drilling -- hole opening</name>
			<description>A specialization of 'drilling'.</description>
		</value>
		<value>
			<name>drilling -- new hole</name>
			<description>A specialization of 'drilling'.</description>
		</value>
		<value>
			<name>drilling -- sidetracking</name>
			<description>A specialization of 'drilling'.</description>
		</value>
		<value>
			<name>drilling -- under-reaming</name>
			<description>A specialization of 'drilling'.</description>
		</value>
		<value>
			<name>fishing</name>
			<description>fishing</description>
		</value>
		<value>
			<name>fishing -- BHA</name>
			<description>A specialization of 'fishing'.</description>
		</value>
		<value>
			<name>fishing -- casing</name>
			<description>A specialization of 'fishing'.</description>
		</value>
		<value>
			<name>fishing -- cones</name>
			<description>>A specialization of 'fishing'.</description>
		</value>
		<value>
			<name>fishing -- other</name>
			<description>A specialization of 'fishing'.</description>
		</value>
		<value>
			<name>fishing -- stuck pipe</name>
			<description>A specialization of 'fishing'.</description>
		</value>
		<value>
			<name>fishing -- wireline tools</name>
			<description>A specialization of 'fishing'.</description>
		</value>
		<value>
			<name>HSE</name>
			<description>Health, Safety and Environmental</description>
		</value>
